export const FETCH_QUIZES_START = 'FETCH_QUIZES_START'
export const FETCH_QUIZES_SUCCES = 'FETCH_QUIZES_SUCCES'
export const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR'


export const FETCH_QUIZ_SUCCES = 'FETCH_QUIZ_SUCCES'

export const QUIZE_SET_STATE = 'QUIZE_SET_STATE'
export const FINISH_QUIZ = 'FINISH_QUIZ'
export const QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION'
export const RETRY_QUIZ = 'RETRY_QUIZ'